import { test, expect } from "@playwright/test";
test("register, create, edit, archive, search, restore, delete and sign out", async ({ page }) => {
  await page.goto("/register");
  await page.getByLabel("Name", { exact: true }).fill("Browser Tester");
  await page.getByLabel("Username", { exact: true }).fill("browser-" + Date.now());
  await page.getByLabel("Email", { exact: true }).fill("browser-" + Date.now() + "@example.test");
  await page.getByLabel("Password", { exact: true }).fill("BrowserPassword123!");
  await page.getByRole("button", { name: "Register", exact: true }).click();
  await page.getByRole("link", { name: "Create Your First Task" }).click();
  await page.getByLabel("Title", { exact: true }).fill("Browser task");
  await page.getByLabel("Content", { exact: true }).fill("Verify the complete task lifecycle");
  await page.getByRole("button", { name: "Create Task", exact: true }).click();
  await page.getByRole("button", { name: "Browser task", exact: true }).click();
  await page.getByLabel("Title", { exact: true }).fill("Edited browser task");
  await page.getByRole("button", { name: "Save Changes" }).click();
  await page.getByRole("button", { name: "Archive task", exact: true }).click();
  await page.getByRole("button", { name: "Yes, archive it!" }).click();
  await page.getByRole("link", { name: "Archived", exact: true }).first().click();
  await page.getByLabel("Search archived tasks").fill("Edited browser");
  await expect(page.getByRole("cell", { name: "Edited browser task", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Unarchive task" }).click();
  await page.getByRole("button", { name: "Yes, unarchive it!" }).click();
  await page.getByRole("link", { name: "Tasks", exact: true }).first().click();
  await page.getByRole("button", { name: "Delete task", exact: true }).click();
  await page.getByRole("button", { name: "Yes, delete it!" }).click();
  await expect(page.getByText("No tasks yet", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Logout", exact: true }).first().click();
  await expect(page.getByRole("link", { name: "Login", exact: true })).toBeVisible();
});
test("demo board, persistent keyboard ordering, pagination and mobile theme", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("Email", { exact: true }).fill("demo@example.test");
  await page.getByLabel("Password", { exact: true }).fill("PortfolioDemo123!");
  await page.getByRole("button", { name: "Login", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Task Board", exact: true })).toBeVisible();
  await expect(page.getByText("Logged in successfully!", { exact: true })).toBeHidden();
  await page.screenshot({ path: "../docs/screenshots/task-board.png", fullPage: true, animations: "disabled" });
  const column = page.locator('[data-rfd-droppable-id="Pending"]');
  const cards = column.locator("[data-rfd-draggable-id]");
  await cards.first().focus();
  await page.keyboard.press("Space");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Space");
  await expect(cards.first()).toContainText("Write regression tests");
  await page.reload();
  await expect(column.locator("[data-rfd-draggable-id]").first()).toContainText("Write regression tests");
  await page.getByRole("link", { name: "Archived", exact: true }).first().click();
  await expect(page.getByRole("cell", { name: "Completed milestone", exact: false }).first()).toBeVisible();
  await page.getByRole("button", { name: "Next", exact: true }).click();
  await expect(page.getByRole("row")).toHaveCount(3);
  await page.screenshot({ path: "../docs/screenshots/archive.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Open menu" }).click();
  await page.getByLabel("Theme", { exact: true }).last().selectOption("dracula");
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dracula");
  await page.getByRole("button", { name: "Close menu", exact: true }).click();
  await expect(page.locator("#drawer")).not.toBeChecked();
  await page.screenshot({ path: "../docs/screenshots/mobile.png", fullPage: true, animations: "disabled" });
});
